from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
LOCATOR_DATASET_DIR = ROOT_DIR / "locator_dataset"
LOCATOR_TRAIN_IMAGE_DIR = LOCATOR_DATASET_DIR / "train" / "images"
LOCATOR_TRAIN_ABDOMEN_DIR = LOCATOR_DATASET_DIR / "train" / "abdomen_masks"
LOCATOR_TRAIN_NAVEL_DIR = LOCATOR_DATASET_DIR / "train" / "navel_masks"
LOCATOR_VAL_IMAGE_DIR = LOCATOR_DATASET_DIR / "val" / "images"
LOCATOR_VAL_ABDOMEN_DIR = LOCATOR_DATASET_DIR / "val" / "abdomen_masks"
LOCATOR_VAL_NAVEL_DIR = LOCATOR_DATASET_DIR / "val" / "navel_masks"
LOCATOR_CHECKPOINT_DIR = ROOT_DIR / "checkpoints"
LOCATOR_CHECKPOINT_PATH = LOCATOR_CHECKPOINT_DIR / "best_anatomy_locator.pt"
LOCATOR_OUTPUT_DIR = ROOT_DIR / "outputs" / "anatomy_locator"

IMAGE_SIZE = 512
BATCH_SIZE = 2
EPOCHS = 120
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4
EARLY_STOPPING_PATIENCE = 20
NUM_WORKERS = 0
SEED = 42

ENCODER_NAME = "resnet34"
USE_IMAGENET_WEIGHTS = True
ABDOMEN_THRESHOLD = 0.5
NAVEL_THRESHOLD = 0.35
NAVEL_LOSS_WEIGHT = 2.0

# Locator v2: 배꼽을 binary 원형 mask가 아니라 Gaussian heatmap으로 학습합니다.
LOCATOR_VERSION = 2
NAVEL_TARGET_TYPE = "gaussian_heatmap"
NAVEL_GAUSSIAN_SIGMA_RATIO = 0.018
MIN_NAVEL_SIGMA = 4.0
MAX_NAVEL_SIGMA = 14.0
NAVEL_HEATMAP_POS_WEIGHT = 8.0
NAVEL_CANDIDATE_PEAK_RATIO = 0.70
NAVEL_MIN_CANDIDATE_PROBABILITY = 0.05

# 기존 코드와의 import 호환을 위해 유지합니다. v2 데이터 생성에서는 사용하지 않습니다.
NAVEL_RADIUS_RATIO = 0.018
MIN_NAVEL_RADIUS = 6
MAX_NAVEL_RADIUS = 18

# 입력 검증용 shape/heatmap 기본값. 실제 배포 전 validation set으로 보정하세요.
MIN_ABDOMEN_SOLIDITY_REVIEW = 0.80
MIN_ABDOMEN_SOLIDITY_HARD = 0.60
MIN_ABDOMEN_EXTENT_REVIEW = 0.45
MIN_ABDOMEN_EXTENT_HARD = 0.30
MIN_ABDOMEN_CORE_WIDTH_RATIO_REVIEW = 0.45
MIN_ABDOMEN_CORE_WIDTH_RATIO_HARD = 0.25
MIN_NAVEL_BOUNDARY_MARGIN_RATIO_REVIEW = 0.05
MIN_NAVEL_BOUNDARY_MARGIN_RATIO_HARD = 0.02
MIN_NAVEL_HEATMAP_CONCENTRATION = 0.55
MAX_NAVEL_HEATMAP_SPREAD_RATIO = 0.15
MAX_NAVEL_CANDIDATE_AREA_RATIO = 0.10

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
