from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent

LOCATOR_DATASET_DIR = ROOT_DIR / "locator_dataset"
LOCATOR_TRAIN_IMAGE_DIR = LOCATOR_DATASET_DIR / "train" / "images"
LOCATOR_TRAIN_ABDOMEN_DIR = LOCATOR_DATASET_DIR / "train" / "abdomen_masks"
LOCATOR_TRAIN_NAVEL_DIR = LOCATOR_DATASET_DIR / "train" / "navel_masks"
LOCATOR_VAL_IMAGE_DIR = LOCATOR_DATASET_DIR / "val" / "images"
LOCATOR_VAL_ABDOMEN_DIR = LOCATOR_DATASET_DIR / "val" / "abdomen_masks"
LOCATOR_VAL_NAVEL_DIR = LOCATOR_DATASET_DIR / "val" / "navel_masks"

LOCATOR_CHECKPOINT_DIR = ROOT_DIR / "checkpoints"
LOCATOR_CHECKPOINT_PATH = LOCATOR_CHECKPOINT_DIR / "best_anatomy_locator.pt"
LOCATOR_OUTPUT_DIR = ROOT_DIR / "outputs" / "anatomy_locator"

IMAGE_SIZE = 512
BATCH_SIZE = 2
EPOCHS = 100
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4
EARLY_STOPPING_PATIENCE = 15
NUM_WORKERS = 0
SEED = 42

ENCODER_NAME = "resnet34"
USE_IMAGENET_WEIGHTS = True

ABDOMEN_THRESHOLD = 0.5
NAVEL_THRESHOLD = 0.35
NAVEL_LOSS_WEIGHT = 2.0
NAVEL_RADIUS_RATIO = 0.018
MIN_NAVEL_RADIUS = 6
MAX_NAVEL_RADIUS = 18

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
